// <auto-generated />
using CityApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityApi.Migrations
{
    [DbContext(typeof(CityContext))]
    [Migration("20250325105637_AddSeedDataForCities")]
    partial class AddSeedDataForCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CityApi.Model.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New York",
                            Province = "New York"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Los Angeles",
                            Province = "California"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chicago",
                            Province = "Illinois"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
